steps:
- name: 'gcr.io/$PROJECT_ID/builder:latest'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    gcloud secrets versions access latest \
      --secret nomulus-tool-cloudbuild-credential > tool-credential.json
- name: 'gcr.io/$PROJECT_ID/builder:latest'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    if [ ${_ENV} == production ]
    then
      project_id="domain-registry"
    else
      project_id="domain-registry-${_ENV}"
    fi

    gcloud auth activate-service-account --key-file=tool-credential.json

    echo HELLO
timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
